#!/usr/bin/env bash
set -euo pipefail

MODE=control
INNOVAD=./src/innovad
RUN_DIR=
DURATION=600
DELAY_MS=1000
DROP_PCT=10
SEED=1337
RELAY_PORT=14800

while (($#)); do
    case "$1" in
        --mode) MODE=$2; shift 2 ;;
        --innovad) INNOVAD=$2; shift 2 ;;
        --run-dir) RUN_DIR=$2; shift 2 ;;
        --duration) DURATION=$2; shift 2 ;;
        --delay-ms) DELAY_MS=$2; shift 2 ;;
        --drop-pct) DROP_PCT=$2; shift 2 ;;
        --seed) SEED=$2; shift 2 ;;
        --relay-port) RELAY_PORT=$2; shift 2 ;;
        *) echo "unknown option: $1" >&2; exit 2 ;;
    esac
done

[[ "$MODE" == control || "$MODE" == experiment ]] || {
    echo "--mode must be control or experiment" >&2; exit 2;
}
[[ -n "$RUN_DIR" ]] || { echo "--run-dir is required" >&2; exit 2; }
mkdir -p "$RUN_DIR/source/regtest" "$RUN_DIR/client/regtest"
ROOT=$(cd "$(dirname "$0")/../../.." && pwd)
RELAY="$ROOT/contrib/forensics/b3v2/b3v2_relay.py"

sed 's/^$/# generated by run_b3v2.sh/' "$ROOT/contrib/forensics/b3v2/source.conf.in" > "$RUN_DIR/source/innova.conf"
sed 's/^$/# generated by run_b3v2.sh/' "$ROOT/contrib/forensics/b3v2/client.conf.in" > "$RUN_DIR/client/innova.conf"
if [[ "$MODE" == control ]]; then
    printf '%s\n' "connect=127.0.0.1:$RELAY_PORT" 'ibdheaderscheduler=0' >> "$RUN_DIR/client/innova.conf"
else
    printf '%s\n' "connect=127.0.0.1:$RELAY_PORT" 'ibdheaderscheduler=1' >> "$RUN_DIR/client/innova.conf"
fi

rpc() { "$INNOVAD" -datadir="$1" -regtest "${@:2}"; }
cleanup() {
    rpc "$RUN_DIR/client" stop >/dev/null 2>&1 || true
    rpc "$RUN_DIR/source" setgenerate false >/dev/null 2>&1 || true
    rpc "$RUN_DIR/source" stop >/dev/null 2>&1 || true
    [[ -n "${RELAY_PID:-}" ]] && kill -INT "$RELAY_PID" 2>/dev/null || true
}
trap cleanup EXIT INT TERM

printf 'mode=%s\nduration_s=%s\ndelay_ms=%s\ndrop_pct=%s\nseed=%s\n' \
    "$MODE" "$DURATION" "$DELAY_MS" "$DROP_PCT" "$SEED" > "$RUN_DIR/profile.txt"
printf 'command_source=%q -datadir=%q -regtest\n' "$INNOVAD" "$RUN_DIR/source" >> "$RUN_DIR/profile.txt"
"$INNOVAD" -datadir="$RUN_DIR/source" -regtest >/dev/null
for _ in {1..30}; do rpc "$RUN_DIR/source" getblockcount >/dev/null 2>&1 && break; sleep 1; done
rpc "$RUN_DIR/source" setgenerate true >/dev/null
sleep 5
SOURCE_READY=$(rpc "$RUN_DIR/source" getblockcount)
printf 'source_height_ready=%s\n' "$SOURCE_READY" >> "$RUN_DIR/profile.txt"

python3 "$RELAY" --listen-port "$RELAY_PORT" --target 127.0.0.1:18444 \
    --delay-ms "$DELAY_MS" --drop-pct "$DROP_PCT" --seed "$SEED" \
    --log "$RUN_DIR/relay.log" >/dev/null 2>&1 &
RELAY_PID=$!
for _ in {1..30}; do grep -q '^.* READY ' "$RUN_DIR/relay.log" 2>/dev/null && break; sleep 1; done
grep -q '^.* READY ' "$RUN_DIR/relay.log"

START=$(date -u +%Y-%m-%dT%H:%M:%SZ)
printf 'start_utc=%s\n' "$START" >> "$RUN_DIR/profile.txt"
rpc "$RUN_DIR/client" -daemon >/dev/null
sleep "$DURATION"
END=$(date -u +%Y-%m-%dT%H:%M:%SZ)
printf 'end_utc=%s\n' "$END" >> "$RUN_DIR/profile.txt"
printf 'source_height_end=%s\n' "$(rpc "$RUN_DIR/source" getblockcount)" >> "$RUN_DIR/profile.txt"
printf 'client_height_end=%s\n' "$(rpc "$RUN_DIR/client" getblockcount)" >> "$RUN_DIR/profile.txt"
